[package]
name = "libm-macros"
version = "0.1.0"
edition = "2024"
publish = false
license = "MIT OR Apache-2.0"

[lib]
proc-macro = true

[dependencies]
heck.workspace = true
proc-macro2.workspace = true
quote.workspace = true
syn = { workspace = true, features = ["full", "extra-traits", "visit-mut"] }

[lints.rust]
# Values used during testing
unexpected_cfgs = { level = "warn", check-cfg = [
  'cfg(f16_enabled)',
  'cfg(f128_enabled)',
] }
