language: rust
rust:
  - stable
  - beta
  - nightly
sudo: false
script:
  - cargo test
  - cargo test --no-default-features
  - cargo test --no-default-features --features 'libunwind'
  - cargo test --no-default-features --features 'libunwind dladdr'
  - cargo test --no-default-features --features 'libunwind libbacktrace'
  - cargo test --no-default-features --features 'unix-backtrace'
  - cargo test --no-default-features --features 'unix-backtrace dladdr'
  - cargo test --no-default-features --features 'unix-backtrace libbacktrace'
  - cargo test --no-default-features --features 'serialize-serde'
  - cargo test --no-default-features --features 'serialize-rustc'
  - cargo test --no-default-features --features 'serialize-rustc serialize-serde'
  - rustdoc --test README.md -L target/debug/deps -L target/debug
  - cargo doc --no-deps
notifications:
  email:
    on_success: never
after_success: |
  [ $TRAVIS_BRANCH = master ] &&
  [ $TRAVIS_PULL_REQUEST = false ] &&
  [ $TRAVIS_RUST_VERSION = nightly ] &&
  echo '<meta http-equiv=refresh content=0;url=backtrace/index.html>' > target/doc/index.html &&
  pip install ghp-import --user $USER &&
  $HOME/.local/bin/ghp-import -n target/doc &&
  git push -qf https://${TOKEN}@github.com/${TRAVIS_REPO_SLUG}.git gh-pages
env:
  global:
    secure: g5hE6I1aheSevWUkVZxL/DUS6cbx2nCrKFcaCpfpvT6zf4uA/FOX2UlaUQO2wAqULj77TVIpOEZG5KyZmFw2yHt8I61z54JQvz8WsaHI4+EzNCBVF542kbNQehDJA7BcevJTL88bGwsZttSBD4GcDw8GkLUfY4Ce1nUydu3haf+iLOmTpdzE9OnNnNcrbQ5l17Lokq3vpIw3FxyUypU1v2FQqTDEtcgS2y3ZSg/qn02f4rU/jds/QhO65PZ2ViXVg2Jn/LbwaOLjFfRuC4OPBXyY318jJkvIcmCjwGWwVaEZOzJDqnCSKkgqEmktv/GoXTWaGuLuFsNcl/qervja3Ixi8bb41lklqBsv6Moyt2pSoeCXbWf4tPWfCAOxE0DCfAkutcrJx0v0etsbLTGh4WnfqwcFEW1NcGxAsoTzaww7S9lM6pyHoyaQ5TnTqGftMTQ8IcaVYsjLG7UwHfkHQqgAcYZ1yukPuxM+DdpOFIHEivzjjSFvpHtQpxCoFS+n72AW8dk+pl2PHpVdWa7TTsIA5QIJoCZ7m4PjG872+ofcriW1Ib5LiwhYlRMhjbQUGFLVZVKRvYiPQubTLBwT62rOaljzz9TrfB+NXHZ+ykcqs1aXavPwGWgBwOks17ApnOInYBUV7j5jm7Pt7pCwsaMg8iMdPxdBu8xk3N1C1Wg=

os:
  - linux
  - osx
