# SPDX-License-Identifier: MIT OR Apache-2.0
# SPDX-FileCopyrightText: The Ferrocene Developers

[files]
"pinned.toml" = "0f9df0ca-03ae-499d-932c-e84b1a0ff027"
"safety-manager.cosign-bundle" = "fa06a652-092d-4075-9a08-021a2bcb3025"
