# SPDX-License-Identifier: MIT OR Apache-2.0
# SPDX-FileCopyrightText: The Ferrocene Developers

[files]
"pinned.toml" = "340c42f2-0c16-46bc-818a-7815f4247b67"
"safety-manager.cosign-bundle" = "13dff751-af0f-4e4c-b662-d1f1646daf23"
