# SPDX-License-Identifier: MIT OR Apache-2.0
# SPDX-FileCopyrightText: The Ferrocene Developers

[files]
"pinned.toml" = "42ff2067-8a05-497c-9bf4-006763dd5b96"
"safety-manager.cosign-bundle" = "a8567643-7c28-488a-9cb2-f5405c18d645"
