# SPDX-License-Identifier: MIT OR Apache-2.0
# SPDX-FileCopyrightText: The Ferrocene Developers

# This file defines all the substitutions available in the Sphinx documentation
# sites using the `ferrocene_qualification` extension.

# look at substitutions.py for the rest of the substitutions

iso_26262_ref = "ISO 26262:2018"
iso_26262_doc = "Road Vehicles - Functional Safety"
iso_26262_ferrocene_asil = "ASIL D"
iso_26262_core_asil = "ASIL B"
iso_26262_ferrocene_tcl = "TCL 3"
iso_26262_ferrocene_tql = "class T3"

iec_61508_ref = "IEC 61508:2010"
iec_61508_doc = "Functional safety of electrical/electronic/programmable electronic safety-related systems"
iec_61508_core_sil = "SIL 2"

iso_9001_ref = "ISO 9001:2015"
iso_9001_doc = "Quality management systems â€” Requirements"

iec_62304_ref = "IEC 62304:2006 + AMD 1:2015"
iec_62304_doc = "Medical device software - Software life cycle processes"
