# SPDX-License-Identifier: MIT OR Apache-2.0
# SPDX-FileCopyrightText: The Ferrocene Developers

# This file defines the human-readable names for the targets supported by
# Ferrocene, to provide consistency across documents on how we refer to them.
#
# In the documents, as long as the ferrocene_qualification extension is added,
# you can refer to them with :target:`triple`.

aarch64-unknown-none     = "Armv8-A bare-metal"
thumbv7em-none-eabi      = "Armv7E-M bare-metal (soft-float)"
thumbv7em-none-eabihf    = "Armv7E-M bare-metal (hard-float)"
armv8r-none-eabihf       = "Armv8-R bare-metal (hard-float)"
wasm32-unknown-unknown   = "WASM bare-metal"
x86_64-unknown-linux-gnu = "x86-64 Linux (glibc)"
