[package]
name = "symbol-check"
version = "0.1.0"
edition = "2024"
publish = false

[dependencies]
object = { version = "0.37.3", features = ["wasm"] }
serde_json = "1.0.149"

[dev-dependencies]
assert_cmd = "2.1.2"
cc = "1.2.55"
tempfile = "3.24.0"
