[package]
name = "symbol-check"
version = "0.1.0"
edition = "2024"
publish = false

[dependencies]
object.workspace = true
regex.workspace = true
serde_json.workspace = true

[dev-dependencies]
assert_cmd.workspace = true
cc.workspace = true
tempfile.workspace = true
