[package]
name = "build_helper"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
<<<<<<< HEAD
serde = "1"
serde_derive = "1"

# Ferrocene additions
serde_json = "1"
similar = "2"
||||||| 7c04f5d216b
serde = "1"
serde_derive = "1"
=======
serde = { version = "1", optional = true }
serde_derive = { version = "1", optional = true }

[features]
metrics = ["dep:serde", "dep:serde_derive"]
>>>>>>> pull-upstream-temp--do-not-use-for-real-code
