# SPDX-License-Identifier: MIT OR Apache-2.0
# SPDX-FileCopyrightText: The Ferrocene Developers

[files]
"pinned.toml" = "b124d253-8d22-4477-9ed9-02924bf63b19"
"safety-manager.cosign-bundle" = "7317fb48-c350-4add-a0a6-0366394f720f"
