# SPDX-License-Identifier: MIT OR Apache-2.0
# SPDX-FileCopyrightText: The Ferrocene Developers

[files]
"pinned.toml" = "c71bf4e6-a70a-46e0-ba26-e3e9b7911bab"
"safety-manager.cosign-bundle" = "78ef7f45-4fd0-478a-a2ef-88a7e4134456"
