# SPDX-License-Identifier: MIT OR Apache-2.0
# SPDX-FileCopyrightText: The Ferrocene Developers

[files]
"pinned.toml" = "8f16b158-8c4d-4f04-bb18-a9758b94c33b"
"safety-manager.cosign-bundle" = "d61f0126-12d0-4abc-82b7-368edb16dd3f"
