# SPDX-License-Identifier: MIT OR Apache-2.0
# SPDX-FileCopyrightText: The Ferrocene Developers

[files]
"pinned.toml" = "25f7e6e9-58f4-423a-9bb4-23c0752fa6b0"
"safety-manager.cosign-bundle" = "398e7727-cb39-48cc-bda8-900d97deda9c"
