# SPDX-License-Identifier: MIT OR Apache-2.0
# SPDX-FileCopyrightText: The Ferrocene Developers

[files]
"pinned.toml" = "36ad8306-57ec-4f2f-9051-0fba8b730a08"
"safety-manager.cosign-bundle" = "28d9edb0-e8ac-4ba6-b008-389a44a75097"
