# SPDX-License-Identifier: MIT OR Apache-2.0
# SPDX-FileCopyrightText: The Ferrocene Developers

[files]
"pinned.toml" = "a52530be-d003-4c24-a5d5-160b395f8202"
"safety-manager.cosign-bundle" = "9a9b1b29-5e96-49ae-aee7-b5346f2ad98f"
