# SPDX-License-Identifier: MIT OR Apache-2.0
# SPDX-FileCopyrightText: The Ferrocene Developers

[files]
"pinned.toml" = "77a91462-557e-4456-9176-c8217f25606e"
"safety-manager.cosign-bundle" = "ab2a7b22-3e18-4723-bc8c-7809babe9dbc"
