[package]
name = "symbol-report"
edition.workspace = true

[dependencies]
build_helper = { path = "../../../src/build_helper", features = ["metrics"] }
serde = { version = "1", features = ["derive"] }
serde_json = "1"
