name: Dist host
run-name: Dist (${{inputs.host-triple}})

defaults:
  run:
    shell: bash

on:
  workflow_call:
    inputs:
      host-triple:
        type: string
        description: The Rust triple of the host platform
      # We cannot specify an array here
      # See: https://docs.github.com/en/actions/writing-workflows/workflow-syntax-for-github-actions#onworkflow_callinputsinput_idtype
      #      https://docs.github.com/en/actions/writing-workflows/workflow-syntax-for-github-actions#onworkflow_dispatchinputs
      triples:
        type: string
        description: A comma separated list of targets to build
      runner:
        type: string
        description: The GitHub Runner to run on
      use-minio:
        type: boolean
        default: false
        description: If minIO should be used (otherwise, S3 is used)
      build-run-id:
        type: string
        description: The run id of the build workflow
      build-artifact:
        type: string
        description: The artifact from the build workflow
      container:
        type: string
        description: The container URI to run the build in, if any (Linux only)
      qnx-version:
        type: string
        default: ""
        description: The QNX version (if any) and BuildID (eg '7.1.0-472' for 7.1.0 BuildID 472)
      artifacts-bucket:
        type: string
        description: The artifact bucket
      artifacts-prefix:
        type: string
        description: The artifact prefix
      cache-bucket:
        type: string
        description: The cache bucket
      cache-prefix:
        type: string
        description: The cache prefix
      environment:
        type: string
    outputs:
      run-id:
        description: The id of the workflow run
        value: ${{ github.run_id }}
      artifact-targets:
        description: The name of the targets artifact
        value: ${{ jobs.targets.outputs.artifact-name }}

env:
  ARTIFACTS_BUCKET: ${{ inputs.artifacts-bucket }}
  ARTIFACTS_PREFIX: ${{ inputs.artifacts-prefix }}
  CACHE_BUCKET: ${{ inputs.cache-bucket }}
  CACHE_PREFIX: ${{ inputs.cache-prefix }}
  AWS_REGION: us-east-1
  AWS_ROLE_ARN: ${{ (github.ref == 'refs/heads/staging') && secrets.AWS_OIDC_GHA_ARN_STAGING || secrets.AWS_OIDC_GHA_ARN_TRYING }}
  FERROCENE_HOST: ${{ inputs.host-triple }}
  FERROCENE_TARGETS: ${{ inputs.triples }}

jobs:
  targets:
    runs-on: ${{ inputs.runner }}
    steps:
      - uses: actions/checkout@v4
      - name: Setup
        uses: ./.github/actions/setup/
        with:
          build-dependencies: ${{ (inputs.container != '') && 'false' || 'true' }}
      
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        if: ${{ inputs.use-minio == false }}
        with:
          aws-region: ${{ env.AWS_REGION }}
          role-to-assume: ${{ env.AWS_ROLE_ARN }}
          role-duration-seconds: 7200

      - name: Restore build cache
        uses: ./.github/actions/restore-build-cache/
        if: ${{ inputs.use-minio == false }}
        with:
          build-artifact: ${{ inputs.build-artifact }}
          build-run-id: ${{ inputs.build-run-id }}
          bucket: ${{ inputs.cache-bucket }}
          prefix: ${{ inputs.cache-prefix }}

      - name: Download QNX
        uses: ./.github/actions/qnx/
        if: ${{ inputs.use-minio == false }}
        with:
          version: ${{ inputs.qnx-version }}

      - name: Restore build cache
        uses: ./.github/actions/restore-build-cache/
        if: ${{ inputs.use-minio == true }}
        env:
          AWS_ENDPOINT_URL: ${{ secrets.CACHE_ENDPOINT_URL }}
          AWS_ACCESS_KEY_ID: ${{ secrets.CACHE_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.CACHE_SECRET_ACCESS_KEY }}
          AWS_CA_BUNDLE: ${{ secrets.CACHE_CA_BUNDLE }}
        with:
          build-artifact: ${{ inputs.build-artifact }}
          build-run-id: ${{ inputs.build-run-id }}
          bucket: ${{ inputs.cache-bucket }}
          prefix: ${{ inputs.cache-prefix }}

      - name: Download QNX
        uses: ./.github/actions/qnx/
        if: ${{ inputs.use-minio == true }}
        env:
          AWS_ENDPOINT_URL: ${{ secrets.CACHE_ENDPOINT_URL }}
          AWS_ACCESS_KEY_ID: ${{ secrets.CACHE_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.CACHE_SECRET_ACCESS_KEY }}
          AWS_CA_BUNDLE: ${{ secrets.CACHE_CA_BUNDLE }}
        with:
          version: ${{ inputs.qnx-version }}

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        if: ${{ inputs.use-minio == true }}
        with:
          aws-region: ${{ env.AWS_REGION }}
          role-to-assume: ${{ env.AWS_ROLE_ARN }}
          role-duration-seconds: 7200

      - name: Run
        uses: ./.github/actions/run/
        with:
          container: ${{ inputs.container }}
          # See ferrocene/ci/split-tasks.py for a list of tasks executed by this.
          script: |
            export QNX_LICENSE_FILE="qnx${{ inputs.qnx-version }}/license/licenses"
            source qnx${{ inputs.qnx-version }}/qnxsdp-env.sh
            
            ./x.py --stage 2 dist rust-std

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        if: ${{ inputs.use-minio == true }}
        with:
          aws-region: ${{ env.AWS_REGION }}
          role-to-assume: ${{ env.AWS_ROLE_ARN }}
          role-duration-seconds: 7200

      - name: Upload artifacts to S3
        env:
          CIRCLE_SHA1: ${{ github.sha }}
          CIRCLE_JOB: ${{ inputs.build-metrics-artifact }}
        run:
          ./ferrocene/ci/scripts/upload-dist-artifacts.sh


