# SPDX-License-Identifier: MIT OR Apache-2.0
# SPDX-FileCopyrightText: The Ferrocene Developers

name: "SBOM"
on:
  workflow_dispatch:
  pull_request:

jobs:
  sbom-gen:
    name: SBOM-Generation
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup submodules and uv
        uses: ./.github/actions/setup/
        with:
          llvm-subset: 'false'
          build-dependencies: 'false'
          setup-uv: 'true'

      - name: Install syft
        run: curl -sSfL https://get.anchore.io/syft | sudo sh -s -- -b /usr/local/bin v1.41.1
          
      - name: Generate SBOMs
        run: ./x.py dist ferrocene-sbom

      - name: Upload generated SBOMs
        uses: actions/upload-artifact@v4
        with:
          name: Generated-SBOMs
          path: build/ferrocene-sbom/*
