name: "SBOM"
on:
  workflow_dispatch:
  pull_request:

jobs:
  sbom-gen:
    name: SBOM-Generation
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup submodules and uv
        uses: ./.github/actions/setup/
        with:
          llvm-subset: 'true'
          build-dependencies: 'false'

      - name: Install cargo-sbom
        run: cargo install cargo-sbom

      - name: Generate SBOMs
        run: ./ferrocene/tools/sbom-gen/sbom_gen.sh

      - name: Upload generated SBOMs
        uses: actions/upload-artifact@v4
        with:
          name: Generated-SBOMs
          path: target/sboms/*

  sbom-merge:
    name: SBOM-Merge
    runs-on: ubuntu-latest
    container: cyclonedx/cyclonedx-cli
    needs: sbom-gen

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        
      - name: Get generated SBOMs from sbom-gen job
        uses: actions/download-artifact@v4
        with:
          name: Generated-SBOMs

      - name: Merge SBOMs
        run: ./ferrocene/tools/sbom-gen/sbom_merge.sh

      - name: Upload SBOM
        uses: actions/upload-artifact@v4
        with:
          name: Ferrocene SBOM
          path: target/sboms/ferrocene_cdx_sbom.json
