# SPDX-License-Identifier: MIT OR Apache-2.0
# SPDX-FileCopyrightText: The Ferrocene Developers

name: "SBOM"
on:
  workflow_dispatch:
  pull_request:

jobs:
  sbom-gen:
    name: SBOM-Generation
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup submodules and uv
        uses: ./.github/actions/setup/
        with:
          llvm-subset: 'true'
          build-dependencies: 'false'
          setup-uv: 'true'

      - name: Prepare yarn
        run: |
          # apt install yarnpkg
          yarnpkg set version 4.12.0
          yarnpkg install
          cat yarn.lock

      - name: Temp tools
        run: |
          cargo install cargo-sbom
          curl -LsSf https://github.com/CycloneDX/cyclonedx-cli/releases/download/v0.29.2/cyclonedx-linux-x64 -o ~/.cargo/bin/cyclonedx

      - name: Generate SBOMs
        run: ./x.py dist ferrocene-sbom

      - name: Upload generated SBOMs
        uses: actions/upload-artifact@v4
        with:
          name: Generated-SBOMs
          path: build/ferrocene-sboms/*
