[package]
name = "util"
version = "0.1.0"
edition = "2024"
publish = false
license = "MIT OR Apache-2.0"

[features]
default = ["build-musl", "build-mpfr", "unstable-float"]
build-musl = ["libm-test/build-musl", "dep:musl-math-sys"]
build-mpfr = ["libm-test/build-mpfr", "dep:rug"]
unstable-float = ["libm/unstable-float", "libm-test/unstable-float", "rug?/nightly-float"]

[dependencies]
libm.workspace = true
libm-macros.workspace = true
libm-test.workspace = true
musl-math-sys = { workspace = true, optional = true }
rug = { workspace = true, optional = true }
